import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  env: {
    AZURE_OPENAI_API_KEY: process.env.AZURE_OPENAI_API_KEY,
    AZURE_OPENAI_ENDPOINT: process.env.AZURE_OPENAI_ENDPOINT,
    AZURE_OPENAI_API_VERSION: process.env.AZURE_OPENAI_API_VERSION,
    AZURE_EMBEDDING_DEPLOYMENT: process.env.AZURE_EMBEDDING_DEPLOYMENT,
    AZURE_EMBEDDING_DEPLOYMENT_LARGE: process.env.AZURE_EMBEDDING_DEPLOYMENT_LARGE,
    AZURE_COMPLETION_DEPLOYMENT_FAST: process.env.AZURE_COMPLETION_DEPLOYMENT_FAST,
    AZURE_COMPLETION_DEPLOYMENT_STANDARD: process.env.AZURE_COMPLETION_DEPLOYMENT_STANDARD,
    AZURE_COMPLETION_DEPLOYMENT_PRECISE: process.env.AZURE_COMPLETION_DEPLOYMENT_PRECISE
  },
};

export default nextConfig;
